data_dir: /home/pervinco/Datasets/BKAI-IGH-NeoPolyp
sample_img: /home/pervinco/Datasets/BKAI-IGH-NeoPolyp/test/test/0a5f3601ad4f13ccf1f4b331a412fc44.jpeg

save_dir: ./runs
pretrained_model_name: nvidia/mit-b5 ## nvidia/segformer-b0-finetuned-ade-512-512

## Training Hyps
num_folds: 3 ## only for cross validations
train_set_idx: 1
resume_weights: null

seed: 1994
epochs: 500
img_size: 512
batch_size: 6
num_workers: 32
learning_rate: 0.00001
weight_decay: 0.001
early_stop_patience: 20

lr_patience: 5
lr_factor: 0.1

warmup_epochs: 200
min_lr: 0.000001
max_lr: 0.0001
T_0: 200
T_mult: 2

## Data Augments
focal_alpha: [1, 1, 1]
focal_gamma: 3
spatial_alpha: 0.3
mixup_alpha: 0.6

## Model Config
num_channels: 3
num_encoder_blocks: 4
depths: [2, 2, 2, 2]
sr_ratios: [8, 4, 2, 1]
hidden_sizes: [32, 64, 160, 256]
patch_sizes: [7, 3, 3, 3]
strides: [4, 2, 2, 2]
num_attention_heads: [1, 2, 5, 8] ## [1, 2, 5, 8]
mlp_ratios: [4, 4, 4, 4]
hidden_act: "gelu"
layer_norm_eps: 0.000001
initializer_range: 0.02

do_reduce_labels: False
semantic_loss_ignore_index: 255
hidden_dropout_prob: 0.2  # dropout 비율 감소
attention_probs_dropout_prob: 0.2  # dropout 비율 유지
classifier_dropout_prob: 0.2  # dropout 비율 감소
drop_path_rate: 0.1  # drop path rate 감소
decoder_hidden_size: 256  ## 512