data_dir: "/home/pervinco/Datasets/PASCAL_VOC/VOCDevkit" # "/home/pervinco/Datasets/COCO2017"
save_dir: "./runs"
pretrained_model_name: "nvidia/mit-b5" # "nvidia/segformer-b0-finetuned-ade-512-512"
sample_img: "./sample/dog.jpg"

epochs: 1000
img_size: 512
batch_size: 4
learning_rate: 0.0001
mIoU_step: 10

lr_patience: 40
min_lr: 0.00001
T_0: 100
T_mult: 2

num_channels: 3
num_encoder_blocks: 4
depths: [2, 2, 2, 2]
sr_ratios: [8, 4, 2, 1]
hidden_sizes: [32, 64, 160, 256]
patch_sizes: [7, 3, 3, 3]
strides: [4, 2, 2, 2]
num_attention_heads: [1, 2, 5, 8]
mlp_ratios: [4, 4, 4, 4]
hidden_act: "gelu"
hidden_dropout_prob: 0.2 # 0
attention_probs_dropout_prob: 0.2 # 0
classifier_dropout_prob: 0.2 # 0.1
initializer_range: 0.02
drop_path_rate: 0.2
layer_norm_eps: 0.000001
decoder_hidden_size: 256
semantic_loss_ignore_index: 255

CLASSES:
  [
    "background",
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person",
    "potted plant",
    "sheep",
    "sofa",
    "train",
    "tv/monitor",
  ]

COLORMAP:
  [
    [0, 0, 0],
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0],
    [192, 0, 0],
    [64, 128, 0],
    [192, 128, 0],
    [64, 0, 128],
    [192, 0, 128],
    [64, 128, 128],
    [192, 128, 128],
    [0, 64, 0],
    [128, 64, 0],
    [0, 192, 0],
    [128, 192, 0],
    [0, 64, 128],
  ]
