data_dir: "/home/pervinco/Datasets/PASCAL_VOC/VOCDevkit/VOC2012"
save_dir: "./runs"
pretrained_model_name: "nvidia/segformer-b0-finetuned-ade-512-512" # "nvidia/mit-b5"

epochs: 1000
img_size: 512
batch_size: 32
learning_rate: 0.001

lr_patience: 40
min_lr: 0.00001
T_0: 100
T_mult: 2

VOC_CLASSES:
  [
    "background",
    "aeroplane",
    "bicycle",
    "bird",
    "boat",
    "bottle",
    "bus",
    "car",
    "cat",
    "chair",
    "cow",
    "diningtable",
    "dog",
    "horse",
    "motorbike",
    "person",
    "potted plant",
    "sheep",
    "sofa",
    "train",
    "tv/monitor",
  ]

VOC_COLORMAP:
  [
    [0, 0, 0],
    [128, 0, 0],
    [0, 128, 0],
    [128, 128, 0],
    [0, 0, 128],
    [128, 0, 128],
    [0, 128, 128],
    [128, 128, 128],
    [64, 0, 0],
    [192, 0, 0],
    [64, 128, 0],
    [192, 128, 0],
    [64, 0, 128],
    [192, 0, 128],
    [64, 128, 128],
    [192, 128, 128],
    [0, 64, 0],
    [128, 64, 0],
    [0, 192, 0],
    [128, 192, 0],
    [0, 64, 128],
  ]
