## "/home/pervinco/Datasets/COCO2017"
## "/home/pervinco/Datasets/PASCAL_VOC/VOCDevkit"

data_dir: "/home/pervinco/Datasets/polyp-dataset"
sample_img: "/home/pervinco/Datasets/polyp-dataset/test/test/4e2a6e51d077bad31c8c5f54ffaa27a6.jpeg"

save_dir: "./runs"
pretrained_model_name: "nvidia/mit-b5" # "nvidia/segformer-b0-finetuned-ade-512-512"

epochs: 1000
img_size: 512
batch_size: 4
mIoU_step: 10

learning_rate: 0.0001
weight_decay: 0.000001

focal_alpha: [1, 2, 1]
spatial_alpha: 0.2
mixup_alpha: 0.6

lr_patience: 40
min_lr: 0.000001
T_0: 200
T_mult: 2

num_channels: 3
num_encoder_blocks: 4
depths: [2, 2, 2, 2]
sr_ratios: [8, 4, 2, 1]
hidden_sizes: [32, 64, 160, 256]
patch_sizes: [7, 3, 3, 3]
strides: [4, 2, 2, 2]
num_attention_heads: [1, 2, 5, 8]
mlp_ratios: [4, 4, 4, 4]
hidden_act: "gelu"
semantic_loss_ignore_index: 0
layer_norm_eps: 0.000001
initializer_range: 0.02

hidden_dropout_prob: 0.3 ## 0.0
attention_probs_dropout_prob: 0.1 ## 0.0
classifier_dropout_prob: 0.2 ## 0.1
drop_path_rate: 0.2 ## 0.1
decoder_hidden_size: 768 ## 256
